export const data =
  [
    {
      id: 1,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п от ${70000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Новый Уренгой",
      selected: false,
    },
    {
      id: 2,
      title: "Ведущий графический дизайнер НЕ УДАЛЕННО",
      paymentFrom: `з/п от ${80000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Москва",
      selected: true,
    },
    {
      id: 3,
      title: "Работник декорации, дизайнер (ТЦ Амбар)",
      paymentFrom: `з/п ${29000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Сменный график работы",
      location: "Самара",
      selected: false,
    },
    {
      id: 4,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п ${55000} `,
      paymentTo: ` - ${95000} `,
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Тюмень",
      selected: false,
    },
    {
      id: 5,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п от ${60000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Новый Уренгой",
      selected: false,
    },
    {
      id: 6,
      title: "Ведущий графический дизайнер",
      paymentFrom: `з/п от ${80000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Москва",
      selected: true,
    },
    {
      id: 7,
      title: "Работник декорации, дизайнер",
      paymentFrom: `з/п ${29000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Сменный график работы",
      location: "Самара",
      selected: false,
    },
    {
      id: 8,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п ${65000} `,
      paymentTo: ` - ${95000} `,
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Тюмень",
      selected: false,
    },
    {
      id: 9,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п от ${70000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Новый Уренгой",
      selected: false,
    },
    {
      id: 10,
      title: "Ведущий графический дизайнер НЕ УДАЛЕННО",
      paymentFrom: `з/п от ${80000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Москва",
      selected: true,
    },
    {
      id: 11,
      title: "Работник декорации, дизайнер",
      paymentFrom: `з/п ${29000}`,
      paymentTo: "",
      currency: "rub",
      schedule: "Сменный график работы",
      location: "Самара",
      selected: false,
    },
    {
      id: 12,
      title: "Менеджер-дизайнер",
      paymentFrom: `з/п ${55000} `,
      paymentTo: ` - ${95000} `,
      currency: "rub",
      schedule: "Полный рабочий день",
      location: "Тюмень",
      selected: false,
    },
  ]

